In [1]:
# check gpu info for a machine with Nvidia GPU.
!nvidia-smi

Sun May  7 19:07:15 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 527.37       Driver Version: 527.37       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   48C    P0    N/A /  N/A |      0MiB /  4096MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
import torch
torch.__version__


'2.0.0+cu118'

In the output of above cell, "2.0.0+cu118" means Pytorch version 2.0 and Cuda Toolkit version 11.8.<br>
Cuda Toolkit is what enables us to run PyTorch code on Nvidia GPUs.

In [3]:
torch.cuda.is_available()

True

# Introduction to Tensors

### A. Creating Tensors.

PyTorch tensors can be created using either torch.tensor() or torch.Tensor().<br>
torch.tensor() automatically sets the datatype of the underlying tensor data based on the passed argument while torch.Tensor() explicitly sets the datatype of the underlying tensor data ignoring the passed input argument as seen below.

In [39]:
torch.tensor([1,2,3]).dtype, torch.Tensor(1,2,3).dtype

(torch.int64, torch.float32)

Hence, if a list of integers is passed as an argument to torch.tensor(), pytorch automatically decides that the underlying dtype of this newly created tensor is an int64 while the same integer list was interpreted as a float32 by torch.Tensor().

Regardless, the newly-formed tensors have the data type Tensor, even though the underlying data type is stored as integers or floats.

#### A.1 Scalar

In [5]:
scalar = torch.tensor(3)
scalar

tensor(3)

In [9]:
scalar.ndim

0

In [11]:
type(scalar)

torch.Tensor

A scalar is a zero-dimensional tensor.

We can also retrieve a python data type of a tensor using item().

In [10]:
scalar.item()

3

In [12]:
type(scalar.item())

int

#### A.2 1D Tensor - Vector

In [22]:
vector = torch.tensor([2,5,9])
vector

tensor([2, 5, 9])

For a PyTorch tensor, the number of dimentions of torch tensor is the total number of pairs of square brackets it has.

In [23]:
vector.ndim

1

Since we can see that there is only one pair of square brackets in vector_example, ndim returns just 1 here.

However, the shape of a tensor is an idea/concept different from the number of dimensions of that tensor.

In [24]:
vector.shape

torch.Size([3])

Since there are one row and three columns in vector_example, hence, the returned shape is 3.

In [4]:
x = torch.empty(3)
x

tensor([0., 0., 0.])

In [8]:
torch.zeros(3)

tensor([0., 0., 0.])

In [9]:
torch.ones(3)

tensor([1., 1., 1.])

#### A.3 2D Tensor

In [30]:
matrix_1 = torch.tensor([[1,2,3],[3,4,5]])
matrix_1

tensor([[1, 2, 3],
        [3, 4, 5]])

In [31]:
matrix_1.ndim

2

In [32]:
matrix_1.shape

torch.Size([2, 3])

In [36]:
matrix_2 = torch.tensor([[1,2,3]])
matrix_2

tensor([[1, 2, 3]])

In [34]:
matrix_2.ndim

2

In [35]:
matrix_2.shape

torch.Size([1, 3])

In [52]:
matrix_3 = torch.tensor([[1,2,3],
                         [4,5,6],
                         [7,8,9]])
matrix_3

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

#### Slicing a torch tensor / Accessing tensor dimensions.

In [43]:
matrix_3[0]

tensor([1, 2, 3])

In [44]:
matrix_3[0][1]

tensor(2)

In [45]:
type(matrix_3[0][1])

torch.Tensor

In [48]:
# checking the underlying data type of a tensor
type(matrix_3[0][1]), (matrix_3[0][1]).dtype

(torch.Tensor, torch.int64)

Even though the data type of the element is torch.Tensor, the underlying data type is int64.m

In [26]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [18]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [17]:
torch.rand(2,3)

tensor([[0.9468, 0.1087, 0.6180],
        [0.1788, 0.9232, 0.9727]])

### 3D Tensor

In [56]:
tensor_1 = torch.tensor([[[1,2,3],
                          [4,5,6],
                          [7,8,9]],
                        
                        [[10,11,12],
                         [13,14,15],
                         [16,17,18]]])
tensor_1

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [57]:
tensor_1.ndim

3

In [58]:
tensor_1.shape

torch.Size([2, 3, 3])

In [59]:
tensor_1[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [60]:
tensor_1[1]

tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])

In [13]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

### n-D tensor

In [66]:
tensor_ndim = torch.tensor([[[[1,2,3],
                            [4,5,6],
                            [7,8,9]],
                            [[10,11,12],
                            [13,14,15],
                            [16,17,18]]],
                            [[[19,20,21],
                            [22,23,24],
                            [25,26,27]],
                            [[28,29,30],
                            [31,32,33],
                            [34,35,36]]]])
tensor_ndim

tensor([[[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],

         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]],


        [[[19, 20, 21],
          [22, 23, 24],
          [25, 26, 27]],

         [[28, 29, 30],
          [31, 32, 33],
          [34, 35, 36]]]])

In [70]:
tensor_ndim.ndim # i.e., the number of square bracket pairs

4

In [71]:
tensor_ndim.shape 

torch.Size([2, 2, 3, 3])

In [15]:
torch.zeros(2,3,2,3,2)

tensor([[[[[0., 0.],
           [0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.],
           [0., 0.]]],


         [[[0., 0.],
           [0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.],
           [0., 0.]]],


         [[[0., 0.],
           [0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.],
           [0., 0.]]]],



        [[[[0., 0.],
           [0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.],
           [0., 0.]]],


         [[[0., 0.],
           [0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.],
           [0., 0.]]],


         [[[0., 0.],
           [0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.],
           [0., 0.]]]]])

### B. Random Tensors
Random tensors are important because many neural networks are initialized to have random weights and biases before they are trained.

#### ASIDE: SEEDING PYTORCH
Seeding PyTorch with a desired number ensures that an experiment can be replicated in the future because the random torch tensors generated are reproducible because of the seeding.

#### Random tensor from a uniform distribution with mean 0 and SD 1.

In [17]:
# here, since the manual seed is set before each run of torch.rand() the same input seed 42,
# thus, torch.rand() with provide the same output even if re-run.
torch.manual_seed(42), torch.cuda.manual_seed(42)

random_tensor = torch.rand((2,3,3), requires_grad = True)
random_tensor

tensor([[[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408]],

        [[0.1332, 0.9346, 0.5936],
         [0.8694, 0.5677, 0.7411],
         [0.4294, 0.8854, 0.5739]]], requires_grad=True)

In [19]:
# returns the number of pairs of square brackets
random_tensor.ndim

3

#### Tensor with image dimensions.
Typically, most of the DL tasks that take images as input will see that the images will have been reduced to 256x256x3 (HxWxC) pixels to decrease the number of features of the input image. Lets create a tensor similart to an image dimensions.

In [20]:
torch.manual_seed(42)
random_image_size_tensor = torch.rand((256,256,3))
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([256, 256, 3]))

1. https://www.youtube.com/watch?v=exaWOE8jvy8&list=PLqnslRFeH2UrcDBWF5mfPGpqQDSta6VK4&index=2
2. https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html