In [1]:
import torch
torch.__version__

'2.0.0+cu118'

#### Addition
If the torch tensors are of the same dimension, addition operation between two tensors is done element-wise.

In [2]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor1 + tensor2

tensor([5, 7, 9])

However, if the tensors are not of the same dimension, torch will broadcast a tensor into the shape of the other tensor if possible.

In [4]:
tensor3 = torch.tensor([1,2,3])
tensor4 = torch.tensor([[1,2,3],
                        [4,5,6]])
tensor3+tensor4

tensor([[2, 4, 6],
        [5, 7, 9]])

Note tha this broadcast is not always possible and can raise an error as shown below.

In [6]:
tensor5 = torch.tensor([1,2,3])

tensor6 = torch.tensor([[[1,2,3,4],
                         [5,6,7,8]]])
tensor5.shape, tensor6.shape


(torch.Size([3]), torch.Size([1, 2, 4]))

In [7]:
tensor5 + tensor6

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 2

Scalars can also be added to tensors.

In [8]:
tensor1 + 1

tensor([2, 3, 4])

torch also has an inbuilt method for addition of torch tensors. It can be used in two ways.

In [21]:
torch.add(tensor1, tensor2)

tensor([5, 7, 9])

In [22]:
tensor1.add(tensor2)

tensor([5, 7, 9])

In [19]:
torch.add(tensor1,1)

tensor([2, 3, 4])

In [20]:
tensor1.add(1)

tensor([2, 3, 4])

#### Subtraction
The rules of subtraction are the same as the rules of addition for tensors. 

In [9]:
tensor1 - tensor2

tensor([-3, -3, -3])

In [10]:
tensor1 - 10

tensor([-9, -8, -7])

#### Multiplication (Element-wise)
Tensors can be multiplied to each other with element-wise multiplication. Similar to tensor addition and multiplication, in order to element-wise multiple two torch tensors, either the shapes of the two tensors should match,

In [15]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor1 * tensor2

tensor([ 4, 10, 18])

or one of the tensors should be able to be broadcast into the shape of another tensor.

In [16]:
tensor3 = torch.tensor([1,2,3])

tensor4 = torch.tensor([[2,2,2],
                        [2,2,2]])
tensor3 * tensor4

tensor([[2, 4, 6],
        [2, 4, 6]])

However, torch also has an inbuild **mul** method that allows the multiplication of two torch tensors. This method can be used in two different ways.

In [17]:
torch.mul(tensor3, tensor4)

tensor([[2, 4, 6],
        [2, 4, 6]])

In [18]:
tensor3.mul(tensor4)

tensor([[2, 4, 6],
        [2, 4, 6]])

A tensor can also be multiplied by a scalar.

In [11]:
tensor1 * 3

tensor([3, 6, 9])

#### Division(TODO)

#### Matrix Multiplication / Dot Product of Matrices
Matrix multiplication of matrix A with shape (m,n) with another matrix B with shape (x,y), represented by A . B, involves the dot product of the rows of matrix A with the columns of the matrix B. For this to happen, the number of elements in a row of matrix A should equal to the number of elements in a column of matrix B, i.e., n should equal x. Further, the shape of the resultant matrix will be (m,y)<br>
PyTorch provides a method **matmul()** that performs matrix multiplication between two matrices. 


In [27]:
matrix1 = torch.tensor([[1,2,3],
                        [4,5,6]])
matrix2 = torch.tensor([[7,8],
                        [10,11],
                        [12,13]])
torch.matmul(matrix1, matrix2)

tensor([[ 63,  69],
        [150, 165]])

The same matmul operation can also be done as:

In [46]:
torch.mm(matrix1, matrix2)

tensor([[ 63,  69],
        [150, 165]])

The same matmul operation can also be done as:

In [47]:
matrix1 = torch.tensor([[1,2,3],
                        [4,5,6]])
matrix2 = torch.tensor([[7,8],
                        [10,11],
                        [12,13]])
matrix1.matmul(matrix2)

tensor([[ 63,  69],
        [150, 165]])

If the number of columns of matrix A does not equal to the number of columns of matrix B, matmul() operation fails.

In [29]:
matrix1 = torch.tensor([[1,2,3],
                        [4,5,6]])
matrix2 = torch.tensor([[7,8, 9],
                        [10,11,12]])
torch.matmul(matrix1, matrix2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

However, matrix multiplication of two matrices can also be achieved in python/torch using a nested for loop, if needed.

Transpose of a Matrix<br>
The transpose of a matrix A is the transformation of the matrix such that its rows are convered into columns and the columns are converted into rows. torch provides multiple ways to transpose a matrix.

In [33]:
matrix1 = torch.tensor([[1,2,3],
                        [4,5,6]])
matrix1.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [39]:
matrix1.transpose(dim0 = 0, dim1 = 1) # needs dim0 and dim1 to be specified. These dimensions are swapped.

tensor([[1, 4],
        [2, 5],
        [3, 6]])