Min, Max, Mean, Sum 

In [1]:
import torch
torch.__version__

'2.0.0+cu118'

In [25]:
x = torch.arange(0,10,1)
x, x.dtype

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.int64)

#### Min and Max

In [7]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [8]:
torch.max(x), x.max()

(tensor(9), tensor(9))

#### Positional min and max : Argmax and Argmin

In [38]:
tensor = torch.rand(5)
tensor

tensor([0.2883, 0.9582, 0.3306, 0.4708, 0.1642])

In [39]:
torch.argmin(tensor), tensor.argmin()

(tensor(4), tensor(4))

In [40]:
torch.argmax(tensor), tensor.argmax()

(tensor(1), tensor(1))

However, notice that if a multidiumensional tensor is passed as an argument, argmin and argmax return the argmin and argmax of the flattened version of the tensor unless the dimension is specified.

In [45]:
tensor = torch.rand((2,6))
tensor

tensor([[0.7826, 0.5342, 0.5150, 0.7841, 0.4592, 0.6016],
        [0.0194, 0.1566, 0.0148, 0.8910, 0.3503, 0.9898]])

In [46]:
torch.argmin(tensor)

tensor(8)

In [48]:
torch.argmin(tensor, dim=0) # 0th dim is the columns

tensor([1, 1, 1, 0, 1, 0])

In [50]:
torch.argmin(tensor, dim=1) # 1st dim is the rows

tensor([4, 2])

#### Mean

torch module has a method mean() to calculate the average value of a 1D tensor. However, the required underlying dtype is float.

In [12]:
torch.mean(x), x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [11]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(4.5000), tensor(4.5000))

In [57]:
tensor = torch.rand((2,3))
tensor

tensor([[0.2057, 0.9225, 0.8496],
        [0.2039, 0.8495, 0.2143]])

In [58]:
torch.mean(tensor.type(torch.float32), dim=0)

tensor([0.2048, 0.8860, 0.5320])

In [59]:
torch.mean(tensor.type(torch.float32), dim=1)

tensor([0.6593, 0.4226])

In [60]:
tensor = torch.rand((2,3,2))
tensor

tensor([[[0.3474, 0.2492],
         [0.3493, 0.9278],
         [0.5702, 0.8017]],

        [[0.9475, 0.3064],
         [0.4379, 0.8767],
         [0.3414, 0.3627]]])

In [61]:
torch.mean(tensor.type(torch.float32), dim=0) # dim == 0 means average across columns

tensor([[0.6474, 0.2778],
        [0.3936, 0.9022],
        [0.4558, 0.5822]])

In [62]:
torch.mean(tensor.type(torch.float32), dim=1) # dim == 1 means average across rows

tensor([[0.4223, 0.6596],
        [0.5756, 0.5152]])

#### Sum

In [24]:
tensor = torch.arange(0, 10, 1.5)
tensor, tensor.dtype

(tensor([0.0000, 1.5000, 3.0000, 4.5000, 6.0000, 7.5000, 9.0000]),
 torch.float32)

In [23]:
torch.sum(tensor), tensor.sum()

(tensor(31.5000), tensor(31.5000))

In [63]:
tensor = torch.rand((2,3,2))
tensor

tensor([[[0.0167, 0.7545],
         [0.3365, 0.6402],
         [0.8058, 0.7599]],

        [[0.4633, 0.4976],
         [0.1042, 0.3649],
         [0.7332, 0.7478]]])

In [64]:
torch.sum(tensor, dim=0) # dim == 0 means across columns

tensor([[0.4800, 1.2521],
        [0.4408, 1.0051],
        [1.5390, 1.5078]])

In [65]:
torch.sum(tensor, dim=1) # dim == 1 means across rows

tensor([[1.1591, 2.1547],
        [1.3007, 1.6103]])