Note: In numpy and torch, the specified axis or dim in any operation gets collapsed. In any tensor, axis/dim 0 is highest dimension, axis/dim 1 is the second-highest dimension and so on. For a 2D tensor, dim 0 is the row direction and dim1 is the column direction. For a 2D tensor, the sum/average/any operation across dim 0 will collapse the rows to produce only one row by performing the operation across the columnwise. 

#### Reshaping
Reshapes a tensor to a pre-defined shape. When possible, the returned tensor will be a view of input instead of a new copy. Otherwise, it will be a copy. Contiguous inputs and inputs with compatible strides can be reshaped without copying.

In [20]:
import torch

Consider a 1D tensor with 18 elements.

In [21]:

tensor = torch.arange(0,18,1)
tensor, tensor.shape

(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17]),
 torch.Size([18]))

While reshaping a tensor, the number of elements after the reshaping should match the number of elements before the reshaping. As such, product of dimensions before reshaping should equal the product of dimensions after reshaping.

In [22]:
tensor_reshaped = tensor.reshape(1,18)
tensor_reshaped, tensor_reshaped.shape

(tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 torch.Size([1, 18]))

In [23]:
tensor_reshaped = tensor.reshape(18, 1)
tensor_reshaped, tensor_reshaped.shape

(tensor([[ 0],
         [ 1],
         [ 2],
         [ 3],
         [ 4],
         [ 5],
         [ 6],
         [ 7],
         [ 8],
         [ 9],
         [10],
         [11],
         [12],
         [13],
         [14],
         [15],
         [16],
         [17]]),
 torch.Size([18, 1]))

Notice the addition of one extra dimension, represented by one extra pair of brackets. 

In [18]:
tensor_reshaped = tensor.reshape(3,6)
tensor_reshaped, tensor_reshaped.shape

(tensor([[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11],
         [12, 13, 14, 15, 16, 17]]),
 torch.Size([3, 6]))

In [19]:
tensor_reshaped = tensor.reshape(2,3,3)
tensor_reshaped, tensor_reshaped.shape

(tensor([[[ 0,  1,  2],
          [ 3,  4,  5],
          [ 6,  7,  8]],
 
         [[ 9, 10, 11],
          [12, 13, 14],
          [15, 16, 17]]]),
 torch.Size([2, 3, 3]))

Note that the product of the dimensions is preserved during the reshaping operation above.<br>
18 == 3 * 6 == 2 * 3 * 3


#### Viewing
Returns a view of an input tensor of a user-assigned shape while keeping the state unchanged in memory. The returned tensor shares the same data and must have the same number of elements, but may have a different size. If it is not possible to view the tensor without copying to a new location in memory, view operation will fail and thus the reshape operation, instead of the view operation, should be used in the expense of a new copy in memory.

In [2]:
tensor =torch.arange(0,9)
tensor, tensor.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]), torch.Size([9]))

In [3]:
tensor_viewed =  tensor.view(1,9)
tensor_viewed, tensor_viewed.shape

(tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8]]), torch.Size([1, 9]))

Notice the addition of one extra dimension, i.e., change in torch.Size attribute. Also both tensor and tensor_viewed share the same RAM memory. Hence, changing tensor_viewed also changes tensor in memory.

In [4]:
tensor_viewed[:,0] = 100
tensor_viewed 

tensor([[100,   1,   2,   3,   4,   5,   6,   7,   8]])

In [5]:
tensor

tensor([100,   1,   2,   3,   4,   5,   6,   7,   8])

It can be seen that changing the element in the view changed the original tensor as well.

#### Stacking
Concatenates a sequence of tensors along a new dimension provided as the argument. By default, the dim is 0, i.e., the highest dimension. Also, appends multiple tensors on top of each other (vstack) or side-by-side(hstack).

In [12]:
tensor = torch.tensor([1,2,3])
tensor, tensor.shape

(tensor([1, 2, 3]), torch.Size([3]))

`tensor` has only one dimension i.e., dim0 is the column dimension. However, for a list of tensors, dim0 becomes the row dimension and torch.stack() will use dim0 / row dimension as the highest dimension to stack the columns.

In [13]:
tensor_stacked = torch.stack([tensor, tensor, tensor], dim = 0)
tensor_stacked

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

However, if stacked at dim1, torch will stack the tensors along the columns.

In [15]:
[tensor, tensor, tensor]

[tensor([1, 2, 3]), tensor([1, 2, 3]), tensor([1, 2, 3])]

In [14]:
tensor_stacked = torch.stack([tensor, tensor, tensor], dim = 1)
tensor_stacked

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

Some more examples.

In [19]:
tensor = torch.tensor([[1],
                       [2],
                       [3]])
tensor

tensor([[1],
        [2],
        [3]])

In [20]:
[tensor, tensor, tensor]

[tensor([[1],
         [2],
         [3]]),
 tensor([[1],
         [2],
         [3]]),
 tensor([[1],
         [2],
         [3]])]

In [21]:
tensor_stacked = torch.stack([tensor, tensor, tensor], dim=0)
tensor_stacked

tensor([[[1],
         [2],
         [3]],

        [[1],
         [2],
         [3]],

        [[1],
         [2],
         [3]]])

In [22]:
tensor_stacked = torch.stack([tensor, tensor, tensor], dim=1)
tensor_stacked

tensor([[[1],
         [1],
         [1]],

        [[2],
         [2],
         [2]],

        [[3],
         [3],
         [3]]])

Notice that the original list of tensors had  2 dimensions. stack() operation added the third dimension.

torch.vstack() stacks tensors vertically/row wise while torch.hstack() stacks tensors horizontally / column wise.

In [28]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

In [29]:
torch.vstack((a,b))

tensor([[1, 2, 3],
        [4, 5, 6]])

In [30]:
torch.hstack((a,b))

tensor([1, 2, 3, 4, 5, 6])

#### Squeeze and Unsqueeze
Squeeze removes all 1 dimension from a tensor and unsqueeze adds a 1 dimension to a tensor.

In [32]:
tensor = torch.tensor([[[1,2,3],
                       [4,5,6]]])
torch.squeeze(tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])

Notice the removal of one dimension above. 

In [37]:
tensor = torch.zeros(1,2,3,4)
tensor, tensor.shape

(tensor([[[[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],
 
          [[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]]]]),
 torch.Size([1, 2, 3, 4]))

In [38]:
torch.squeeze(tensor) # can also use tensor.squeeze()

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [35]:
torch.squeeze(tensor).shape

torch.Size([2, 3, 4])

unsqueezqe() returns a new tensor with a dimension of size 1 inserted at the specific dimension position provided by the user.
explanation: https://stackoverflow.com/questions/57237352/what-does-unsqueeze-do-in-pytorch

#### unsqueeze() for 1D tensor

In [72]:
tensor = torch.tensor([1,2,3])
tensor, tensor.shape

(tensor([1, 2, 3]), torch.Size([3]))

In [73]:
tensor = torch.tensor([1,2,3])
unsqueezed = torch.unsqueeze(tensor, dim=0)
unsqueezed, unsqueezed.shape

(tensor([[1, 2, 3]]), torch.Size([1, 3]))

In [74]:
tensor = torch.tensor([1,2,3])
unsqueezed = torch.unsqueeze(tensor, dim=1)
unsqueezed, unsqueezed.shape

(tensor([[1],
         [2],
         [3]]),
 torch.Size([3, 1]))

Note that a tensor with n dimensions can be unsqueezed only at dimensions between 0 and n-1, as shown below.

In [85]:
tensor = torch.tensor([1,2,3])
unsqueezed = torch.unsqueeze(tensor, dim=2)
unsqueezed, unsqueezed.shape

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

#### unsqueeze() for 2D tensor

In [89]:
tensor = torch.tensor([[1,2,3],[4,5,6]])
tensor, tensor.shape

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 torch.Size([2, 3]))

Notice that the original 2D tensor has one no channel info, only rows and columns info since only 2 square brackets pairs at the ends of the tensor. 

In [90]:
unsqueezed = torch.unsqueeze(tensor, dim=0)
unsqueezed, unsqueezed.shape

(tensor([[[1, 2, 3],
          [4, 5, 6]]]),
 torch.Size([1, 2, 3]))

Squeezing it at dim 0 adds channel dimension i.e., 1 x 2 x 3 where 1 specifies that the tensor has only one channel.

In [95]:
tensor = torch.tensor([[1,2,3],[4,5,6]])
tensor, tensor.shape


(tensor([[1, 2, 3],
         [4, 5, 6]]),
 torch.Size([2, 3]))

In [96]:
unsqueezed = torch.unsqueeze(tensor, dim=1)
unsqueezed, unsqueezed.shape

(tensor([[[1, 2, 3]],
 
         [[4, 5, 6]]]),
 torch.Size([2, 1, 3]))

Squeezing it at dim 1 adds two channels instead of one channel and each channel contains one row and three columns, i.e., 2 x 1 x3.

In [97]:
tensor = torch.tensor([[1,2,3],[4,5,6]])
tensor, tensor.shape


(tensor([[1, 2, 3],
         [4, 5, 6]]),
 torch.Size([2, 3]))

In [98]:
unsqueezed = torch.unsqueeze(tensor, dim=2)
unsqueezed, unsqueezed.shape

(tensor([[[1],
          [2],
          [3]],
 
         [[4],
          [5],
          [6]]]),
 torch.Size([2, 3, 1]))

Squeezing it at dim 2 gives out two channels and two rows but only 1 column, i.e., 2 x 3 x 1

#### Permute
Returns a **view** of the tensor with dimensions swapped in a certain way. Typically used with image data where images are of shape 224 x 224 x 3 where 224 and 224 represent the height and width of the image and 3 represents color channels R, B, G.

In [103]:
tensor = torch.rand((224, 224,3))
tensor.shape

torch.Size([224, 224, 3])

Suppose, we want to use the color channel as the first dimension and the first dimension as the channel

In [104]:
tensor_permutted = tensor.permute(2,0,1) # where 2, 0, 1 are the dimension positions of color channels, height, width that we want to swap
tensor_permutted.shape

torch.Size([3, 224, 224])