Indexing or slicing tensors in PyTorch is similart to numpy.

In [4]:
import torch
torch.__version__

'2.0.0+cu118'

Indexing

In [5]:
tensor = torch.arange(0,9).reshape((1,3,3))
tensor, tensor.shape

(tensor([[[0, 1, 2],
          [3, 4, 5],
          [6, 7, 8]]]),
 torch.Size([1, 3, 3]))

In [6]:
tensor[0]

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [7]:
tensor[0][0]

tensor([0, 1, 2])

In [8]:
tensor[0][1][0]

tensor(3)

Since the outermost dimension has only one element, if we try to access the second element from `tensor`, it throws an error.

In [9]:
tensor[1]

IndexError: index 1 is out of bounds for dimension 0 with size 1

A semicolon `:` can be used to retrieve all the elements of a given dimension. Note that the usage is `tensor[:,0]` and not `tensor[:][0]`since these two have different outputs.

In [14]:
tensor = torch.arange(0,18).reshape((2,3,3))
tensor, tensor.shape

(tensor([[[ 0,  1,  2],
          [ 3,  4,  5],
          [ 6,  7,  8]],
 
         [[ 9, 10, 11],
          [12, 13, 14],
          [15, 16, 17]]]),
 torch.Size([2, 3, 3]))

In [16]:
tensor[:,0] # from all the elements of the highest dimension, return the 0th item.

tensor([[ 0,  1,  2],
        [ 9, 10, 11]])

In [17]:
tensor[:,:,1]

tensor([[ 1,  4,  7],
        [10, 13, 16]])

Notice the difference between the following two.

In [19]:
tensor = torch.arange(0,9).reshape((1,3,3))
tensor, tensor.shape


(tensor([[[0, 1, 2],
          [3, 4, 5],
          [6, 7, 8]]]),
 torch.Size([1, 3, 3]))

In [21]:
tensor[:,1,1], tensor[:,1,1].shape

(tensor([4]), torch.Size([1]))

In [22]:
tensor[0,1,1], tensor[0,1,1].shape

(tensor(4), torch.Size([]))

Since a colon `:` takes all elements, hences it returns a tensor with 1 dimension while not using a colon `:` returns a scalar with no dimension.