Sometimes, data is available as a numpy array, also called ndarray, and we need to use this data in pytorch as a torch tensor. torch has a method to convert an ndarray into torch tensor as `torch.from_numpy(ndarray)`. Similarly, a torch tensor can also be converted into a numpy array as `torch.Tensor.numpy()`.

In [2]:
import numpy as np
import torch
torch.__version__

'2.0.0+cu118'

In [3]:
ndarray = np.arange(1., 9.)
ndarray

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [4]:
tensor = torch.from_numpy(ndarray)
tensor

tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64)

Note that the dtype for a tensor created from a numpy array is float64 because numpy's default decimal number dtype is float64 and it gets transferred over when a tensor is created from a numpy array. However, note that for torch, the default data type when a decimal tensor is created is float32.

In [5]:
ndarray.dtype

dtype('float64')

In order to save computation and train faster, the tensor can explicitly be created with float32 as below while creating a tensor from a numpy array.

In [7]:
tensor = torch.from_numpy(ndarray).type(torch.float32)
tensor, tensor.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.float32)

#### Changing the value a numpy array that was used to create a tensor.

In [12]:
ndarray = np.arange(1.,8.)
tensor = torch.from_numpy(ndarray).type(torch.float32)

In [14]:
ndarray

array([1., 2., 3., 4., 5., 6., 7.])

In [15]:
tensor, tensor.dtype

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.float32)

In [16]:
# change the data in the ndarray and see if this changes the torch tensor

In [17]:

ndarray = ndarray + 1
ndarray

array([2., 3., 4., 5., 6., 7., 8.])

In [18]:
tensor

tensor([1., 2., 3., 4., 5., 6., 7.])

Turns out that torch creates a copy of the numpy array in memory so that the array and the tensor are independent from each other in memory and altering the elements of one doesn't alter the elements of the other. What about the other way around?

In [23]:
tensor = torch.ones(9)
tensor

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
numpy_from_tensor = tensor.numpy()
numpy_from_tensor

array([1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

Notice that the data type has been retained when a torch tensor with dtype float32 is converted into a numpy array even though the default float data type is float64 for numpy.

Will altering the original tensor affect the newly-created numpy array?

In [25]:
tensor = tensor + 1
tensor

tensor([2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [26]:
numpy_from_tensor

array([1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

As seen above, the newly created numpy array does not share memory with the original source tensor and are independent of each other.