Since torch is mostly used for neural networks that are initialized with random numbers, torch initializes the neural network weights and biases. However, in order to make the experiments reproducible, any such initiaization needs to be stored so that the experiment returns the same output if re-run with the same intial weights and biases. Pytorch provides us a way to seed a neural network such that the initialization values of weights and biases can be reproduced if just the seed used before the initialization is stored.

In [2]:
import torch
torch.__version__

'2.0.0+cu118'

In [15]:
torch.rand(1,5, device = "cpu")

tensor([[0.6130, 0.0101, 0.3984, 0.0403, 0.1563]], device='cuda:0')

In [16]:
torch.rand(1,5, device = "cpu")

tensor([[0.9877, 0.1289, 0.5621, 0.5221, 0.7445]], device='cuda:0')

As seen above, two runs of the same code return different outputs. Lets fix the seed to a number and see how rand() behaves.

In [23]:
RANDOM_SEED = 42

In [24]:
torch.manual_seed(RANDOM_SEED)
torch.rand(1,5, device = "cpu")

tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904]])

In [25]:
torch.manual_seed(RANDOM_SEED)
torch.rand(1,5, device = "cpu")

tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904]])

Note that the manual_seed() needs to be set everytime a new block of code is run in Jupyter Notebook, else it will not reproduce the same set of random numbers. If using in a python file, a single call at the top of the code should suffice.