In [1]:
import torch
torch.__version__

'2.0.0+cu118'

In [2]:
# check if GPU is available for GPU computations or not.
torch.cuda.is_available()

True

We can set up device-agnostic code such that if a GPU is available, then the GPU is automatically used for computation and if not available, then CPU is used without throwing any exception.

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
tensor = torch.arange(1,10, device = device)
tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], device='cuda:0')

In [6]:
torch.cuda.device_count()

1

Automatically putting tensors on GPU.

Method 1

In [11]:
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor = torch.tensor([1,2,3], device=device)
tensor, tensor.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

Method 2

In [13]:
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor = torch.tensor([1,2,3])
tensor = tensor.to(device)
tensor, tensor.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

Note that tensors on GPU cannot be directly converted to numpy arrays and first need to be converted to CPU tensor.

In [16]:
# move GPU tensor to cpu
tensor = tensor.to(device = "cpu")
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [17]:
# create a numpy array from the tensor
ndarray = tensor.numpy()
ndarray

array([1, 2, 3], dtype=int64)