In [2]:
import torch
torch.cuda.is_available()

True

### 1D Tensor

In [4]:
x = torch.empty(3)
x

tensor([0., 0., 0.])

In [8]:
torch.zeros(3)

tensor([0., 0., 0.])

In [9]:
torch.ones(3)

tensor([1., 1., 1.])

### 2D Tensor

In [16]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [18]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [17]:
torch.rand(2,3)

tensor([[0.9468, 0.1087, 0.6180],
        [0.1788, 0.9232, 0.9727]])

### 3D Tensor

In [13]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

### n-D tensor

In [15]:
torch.zeros(2,3,2,3,2)

tensor([[[[[0., 0.],
           [0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.],
           [0., 0.]]],


         [[[0., 0.],
           [0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.],
           [0., 0.]]],


         [[[0., 0.],
           [0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.],
           [0., 0.]]]],



        [[[[0., 0.],
           [0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.],
           [0., 0.]]],


         [[[0., 0.],
           [0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.],
           [0., 0.]]],


         [[[0., 0.],
           [0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.],
           [0., 0.]]]]])

1. https://www.youtube.com/watch?v=exaWOE8jvy8&list=PLqnslRFeH2UrcDBWF5mfPGpqQDSta6VK4&index=2
2. https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html